name: auralia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.2.7+11

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  spotify_sdk: ^2.3.0
  supabase_flutter: ^1.4.0
  url_launcher: ^6.1.9
  line_icons: ^2.0.1
  flutter_svg: ^1.1.6
  workmanager: ^0.5.1
  logger: ^1.1.0
  chopper: ^6.1.0
  flutter_activity_recognition:
    git: 
      url: https://github.com/Flajt/flutter_activity_recognition2
      ref: upgrade-play-service-location
  permission_handler: ^10.2.0
  flutter_isolate: ^2.0.4
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  spotify_web_api:
    git: https://github.com/Flajt/spotify_web_api
  flutter_foreground_task: ^4.1.0
  async: ^2.9.0
  geolocator: ^9.0.2
  flutter_secure_storage: ^8.0.0
  shared_preferences: ^2.0.18
  elegant_notification: ^1.6.4
  sentry_flutter: ^6.22.0
  internet_connection_checker: ^1.0.0+1
  flutter_inappwebview: ^5.7.2+3
  data_table_2: ^2.4.1
  bloc: ^8.1.1
  flutter_bloc: ^8.1.2
  get_it: ^7.2.0
  equatable: ^2.0.5
  bloc_concurrency: ^0.2.1
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  chopper_generator: ^6.0.0
  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  isar_generator: ^3.0.5
  flutter_launcher_icons: ^0.12.0


flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/listeningToMusic.svg
  #   - images/a_dot_ham.jpeg